name: sunflower
description: "Приложение для рисования семечек подсолнуха"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.11
  url_launcher: ^6.1.11
  open_file: ^3.5.10
  permission_handler: ^11.4.0
  device_info_plus: ^9.1.2
  json_annotation: ^4.9.0
  intl: ^0.20.2
  uuid: ^4.5.1
  permission_handler_windows: ^0.2.1
  flutter_launcher_icons: ^0.13.1
  math_expressions: ^2.3.0
  shared_preferences: ^2.2.2
  dio: ^5.3.3
  flutter_pdfview: 1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: 
    image_path: "assets/icon/icon.ico"
  ios:
    image_path: "assets/icon/icon.ico"
  windows:
    image_path: "assets/icon/icon.ico"

flutter:
  uses-material-design: true
  assets: 
    - assets/frame.png
    - assets/sunflower.png
    - assets/sunflower_1.jpg
    - assets/sunflower_2.jpg
    - assets/sunflower_3.jpg
    - assets/sunflower_math.pdf